### PR TITLE
Update and Organize stuff in config-example.json

### PR DESCRIPTION
**Pull request by OxyZachary**

### CODE REVIEW

**Comment by Luxxy-GF** [comment]
Need to add the lavalink part in

**Comment by OxyZachary** [comment]
> Need to add the lavalink part in

Yeah, I saw.

**Comment by OxyZachary** [comment]
I have added the lavalink part just now.

**Comment by Luxxy-GF** [comment]
When lavalink don’t work if you can see what I messed up with

**Pull request merged**
